# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from genmos_object_search.grpc import genmos_object_search_pb2 as genmos__object__search_dot_grpc_dot_genmos__object__search__pb2


class GenMOSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/CreateAgent',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentReply.FromString,
                )
        self.GetAgentCreationStatus = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/GetAgentCreationStatus',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusReply.FromString,
                )
        self.UpdateSearchRegion = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/UpdateSearchRegion',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionReply.FromString,
                )
        self.ProcessObservation = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/ProcessObservation',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationReply.FromString,
                )
        self.GetObjectBeliefs = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/GetObjectBeliefs',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsReply.FromString,
                )
        self.GetRobotBelief = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/GetRobotBelief',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefReply.FromString,
                )
        self.CreatePlanner = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/CreatePlanner',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerReply.FromString,
                )
        self.PlanAction = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/PlanAction',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionReply.FromString,
                )
        self.ListenServer = channel.unary_stream(
                '/genmos_object_search.grpc.GenMOS/ListenServer',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerReply.FromString,
                )
        self.Reset = channel.unary_unary(
                '/genmos_object_search.grpc.GenMOS/Reset',
                request_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetRequest.SerializeToString,
                response_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetReply.FromString,
                )


class GenMOSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentCreationStatus(self, request, context):
        """Get agent status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSearchRegion(self, request, context):
        """More fine-grained rpcs for specific functionality
        Update search region by interpreting sensor data such as point cloud.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessObservation(self, request, context):
        """Process observation such as object detection or language, update agent belief
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetObjectBeliefs(self, request, context):
        """Get current belief about where the object is over the search region
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotBelief(self, request, context):
        """Get current belief about the robot state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlanner(self, request, context):
        """Initialize a planner
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlanAction(self, request, context):
        """Calls the planner to return an action for execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenServer(self, request, context):
        """receives messages from server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """reset
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenMOSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentReply.SerializeToString,
            ),
            'GetAgentCreationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentCreationStatus,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusReply.SerializeToString,
            ),
            'UpdateSearchRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSearchRegion,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionReply.SerializeToString,
            ),
            'ProcessObservation': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessObservation,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationReply.SerializeToString,
            ),
            'GetObjectBeliefs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetObjectBeliefs,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsReply.SerializeToString,
            ),
            'GetRobotBelief': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotBelief,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefReply.SerializeToString,
            ),
            'CreatePlanner': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlanner,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerReply.SerializeToString,
            ),
            'PlanAction': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanAction,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionReply.SerializeToString,
            ),
            'ListenServer': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenServer,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerReply.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetRequest.FromString,
                    response_serializer=genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'genmos_object_search.grpc.GenMOS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GenMOS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/CreateAgent',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreateAgentReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentCreationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/GetAgentCreationStatus',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetAgentCreationStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSearchRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/UpdateSearchRegion',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.UpdateSearchRegionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ProcessObservation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/ProcessObservation',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ProcessObservationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetObjectBeliefs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/GetObjectBeliefs',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetObjectBeliefsReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotBelief(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/GetRobotBelief',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.GetRobotBeliefReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatePlanner(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/CreatePlanner',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.CreatePlannerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PlanAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/PlanAction',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.PlanActionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListenServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/genmos_object_search.grpc.GenMOS/ListenServer',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ListenServerReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/genmos_object_search.grpc.GenMOS/Reset',
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetRequest.SerializeToString,
            genmos__object__search_dot_grpc_dot_genmos__object__search__pb2.ResetReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
