# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: observation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11observation.proto\x12\x13sloop_object_search\x1a\x0c\x63ommon.proto\"\xd3\x01\n\rOccupancyGrid\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.sloop_object_search.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x36\n\x05grids\x18\x03 \x03(\x0b\x32\'.sloop_object_search.OccupancyGrid.Grid\x1aK\n\x04Grid\x12&\n\x03pos\x18\x01 \x01(\x0b\x32\x19.sloop_object_search.Vec2\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\"\xc2\x01\n\nPointCloud\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.sloop_object_search.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x35\n\x06points\x18\x03 \x03(\x0b\x32%.sloop_object_search.PointCloud.Point\x1a>\n\x05Point\x12&\n\x03pos\x18\x01 \x01(\x0b\x32\x19.sloop_object_search.Vec3\x12\r\n\x05label\x18\x02 \x01(\t\"\xf1\x01\n\x0fObjectDetection\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.sloop_object_search.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x44\n\ndetections\x18\x03 \x03(\x0b\x32\x30.sloop_object_search.ObjectDetection.Detection3D\x1aY\n\x0b\x44\x65tection3D\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\'\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x1a.sloop_object_search.Box3D\"W\n\x08Language\x12+\n\x06header\x18\x01 \x01(\x0b\x32\x1b.sloop_object_search.Header\x12\x10\n\x08robot_id\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\tb\x06proto3')



_OCCUPANCYGRID = DESCRIPTOR.message_types_by_name['OccupancyGrid']
_OCCUPANCYGRID_GRID = _OCCUPANCYGRID.nested_types_by_name['Grid']
_POINTCLOUD = DESCRIPTOR.message_types_by_name['PointCloud']
_POINTCLOUD_POINT = _POINTCLOUD.nested_types_by_name['Point']
_OBJECTDETECTION = DESCRIPTOR.message_types_by_name['ObjectDetection']
_OBJECTDETECTION_DETECTION3D = _OBJECTDETECTION.nested_types_by_name['Detection3D']
_LANGUAGE = DESCRIPTOR.message_types_by_name['Language']
OccupancyGrid = _reflection.GeneratedProtocolMessageType('OccupancyGrid', (_message.Message,), {

  'Grid' : _reflection.GeneratedProtocolMessageType('Grid', (_message.Message,), {
    'DESCRIPTOR' : _OCCUPANCYGRID_GRID,
    '__module__' : 'observation_pb2'
    # @@protoc_insertion_point(class_scope:sloop_object_search.OccupancyGrid.Grid)
    })
  ,
  'DESCRIPTOR' : _OCCUPANCYGRID,
  '__module__' : 'observation_pb2'
  # @@protoc_insertion_point(class_scope:sloop_object_search.OccupancyGrid)
  })
_sym_db.RegisterMessage(OccupancyGrid)
_sym_db.RegisterMessage(OccupancyGrid.Grid)

PointCloud = _reflection.GeneratedProtocolMessageType('PointCloud', (_message.Message,), {

  'Point' : _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
    'DESCRIPTOR' : _POINTCLOUD_POINT,
    '__module__' : 'observation_pb2'
    # @@protoc_insertion_point(class_scope:sloop_object_search.PointCloud.Point)
    })
  ,
  'DESCRIPTOR' : _POINTCLOUD,
  '__module__' : 'observation_pb2'
  # @@protoc_insertion_point(class_scope:sloop_object_search.PointCloud)
  })
_sym_db.RegisterMessage(PointCloud)
_sym_db.RegisterMessage(PointCloud.Point)

ObjectDetection = _reflection.GeneratedProtocolMessageType('ObjectDetection', (_message.Message,), {

  'Detection3D' : _reflection.GeneratedProtocolMessageType('Detection3D', (_message.Message,), {
    'DESCRIPTOR' : _OBJECTDETECTION_DETECTION3D,
    '__module__' : 'observation_pb2'
    # @@protoc_insertion_point(class_scope:sloop_object_search.ObjectDetection.Detection3D)
    })
  ,
  'DESCRIPTOR' : _OBJECTDETECTION,
  '__module__' : 'observation_pb2'
  # @@protoc_insertion_point(class_scope:sloop_object_search.ObjectDetection)
  })
_sym_db.RegisterMessage(ObjectDetection)
_sym_db.RegisterMessage(ObjectDetection.Detection3D)

Language = _reflection.GeneratedProtocolMessageType('Language', (_message.Message,), {
  'DESCRIPTOR' : _LANGUAGE,
  '__module__' : 'observation_pb2'
  # @@protoc_insertion_point(class_scope:sloop_object_search.Language)
  })
_sym_db.RegisterMessage(Language)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OCCUPANCYGRID._serialized_start=57
  _OCCUPANCYGRID._serialized_end=268
  _OCCUPANCYGRID_GRID._serialized_start=193
  _OCCUPANCYGRID_GRID._serialized_end=268
  _POINTCLOUD._serialized_start=271
  _POINTCLOUD._serialized_end=465
  _POINTCLOUD_POINT._serialized_start=403
  _POINTCLOUD_POINT._serialized_end=465
  _OBJECTDETECTION._serialized_start=468
  _OBJECTDETECTION._serialized_end=709
  _OBJECTDETECTION_DETECTION3D._serialized_start=620
  _OBJECTDETECTION_DETECTION3D._serialized_end=709
  _LANGUAGE._serialized_start=711
  _LANGUAGE._serialized_end=798
# @@protoc_insertion_point(module_scope)
