# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sloop_object_search.grpc import sloop_object_search_pb2 as sloop__object__search_dot_grpc_dot_sloop__object__search__pb2


class SloopObjectSearchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateAgent = channel.unary_unary(
                '/sloop_object_search.grpc.SloopObjectSearch/CreateAgent',
                request_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentRequest.SerializeToString,
                response_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentReply.FromString,
                )
        self.GetAgentCreationStatus = channel.unary_unary(
                '/sloop_object_search.grpc.SloopObjectSearch/GetAgentCreationStatus',
                request_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusRequest.SerializeToString,
                response_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusReply.FromString,
                )
        self.UpdateSearchRegion = channel.unary_unary(
                '/sloop_object_search.grpc.SloopObjectSearch/UpdateSearchRegion',
                request_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionRequest.SerializeToString,
                response_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionReply.FromString,
                )


class SloopObjectSearchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentCreationStatus(self, request, context):
        """Get agent status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSearchRegion(self, request, context):
        """More fine-grained rpcs for specific functionality
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SloopObjectSearchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAgent,
                    request_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentRequest.FromString,
                    response_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentReply.SerializeToString,
            ),
            'GetAgentCreationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentCreationStatus,
                    request_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusRequest.FromString,
                    response_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusReply.SerializeToString,
            ),
            'UpdateSearchRegion': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSearchRegion,
                    request_deserializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionRequest.FromString,
                    response_serializer=sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sloop_object_search.grpc.SloopObjectSearch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SloopObjectSearch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sloop_object_search.grpc.SloopObjectSearch/CreateAgent',
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentRequest.SerializeToString,
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.CreateAgentReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgentCreationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sloop_object_search.grpc.SloopObjectSearch/GetAgentCreationStatus',
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusRequest.SerializeToString,
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.GetAgentCreationStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSearchRegion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sloop_object_search.grpc.SloopObjectSearch/UpdateSearchRegion',
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionRequest.SerializeToString,
            sloop__object__search_dot_grpc_dot_sloop__object__search__pb2.UpdateSearchRegionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
