#!/usr/bin/env python
import rospy
from sloop_object_search_ros.sloop_mos import SloopMosAgentROSBridge

def main():
    rospy.init_node("run_agent")
    config = rospy.get_param("~config")  # access parameters together as a dictionary

    ros_config = config.get("ros_config", {})
    bridge = SloopMosAgentROSBridge(ros_config=ros_config)
    rospy.loginfo("setting up SloopMosAgentROSBridge")
    bridge.setup()
    rate = rospy.Rate(5)
    ready = False
    while not rospy.is_shutdown():
        if bridge.check_if_ready():
            ready = True
            break
        rospy.logwarn("bridge not ready")
        rate.sleep()
    rospy.loginfo("bridge ready!")
    if ready:
        bridge.init_agent(config)
        bridge.init_planner(config)
        rospy.loginfo("sloop agent created. Start running")
        bridge.run()


if __name__ == "__main__":
    main()
