# The original SLOOP: action spaces are low-level
# on top of a grid map

# Transition Model
transition_model: sloop_ros.generic.SLOOPTransitionModel
robot_trans_model: default

# Observation Model
observation_model: sloop_ros.basic.JointObservationModel

# Reward Model
reward_model: sloop_ros.basic.RewardModel

# Policy Model
policy_model: sloop_ros.basic.LowLevelPolicyModel2D

# Belief
belief_dist: sloop_ros.basic.JointBelief
belief_params:
  init_belief: uniform
  object_belief: sloop_ros.basic.LowLevelObjectBelief2D
  robot_belief: sloop_ros.basic.ObservableRobotBelief2D

# Agent
agent: sloop_ros.basic.SLOOPBasicAgent

# Planner
planner: pomdp_py.POUCT
