#!/usr/bin/env python3

import rospy
from sloop_ros.core.instantiate import (create_models,
                                        initialize_belief,
                                        create_agent,
                                        create_planner)

def main():
    rospy.init_node(f"run_pomdp_agent")
    pomdp_name = rospy.get_param("~pomdp_name")
    config = rospy.get_param("~config")  # access parameters together as a dictionary
    models = create_models(config)
    belief = initialize_belief(config)
    agent = create_agent(belief, models, config)
    planner = create_planner(config)
    agent.set_planner(planner)
    agent.setup()  # sets up the subscribers, publishers, services etc.
    agent.run()
    print("HELLO")

if __name__ == "__main__":
    main()
