#!/usr/bin/env python3

import rospy
import pomdp_py
from sloop_ros.core.instantiate import (create_models,
                                        initialize_belief,
                                        create_agent,
                                        create_planner)

def main():
    rospy.init_node(f"run_pomdp_agent")
    pomdp_name = rospy.get_param("~pomdp_name")
    config = rospy.get_param("~config")  # access parameters together as a dictionary
    models = create_models(config)
    belief = initialize_belief(config)
    agent = create_agent(belief, models, config)
    rollout_policy=agent.policy_model
    # TODO: ugly code; use set_rollout_policy if using pomdp_py>=1.3.3
    if "POUCT" in config["planner"] or "POMCP" in config["planner"]:
        planner = create_planner(config, rollout_policy=agent.policy_model)
    else:
        planner = create_planner(config)
    agent.set_planner(planner)
    agent.setup()  # sets up the subscribers, publishers, services etc.
    agent.run()

if __name__ == "__main__":
    main()
