#!/usr/bin/env python
import rospy
from sloop_object_search.ros.sloop_mos import SloopMosAgentROSRunner

def main():
    rospy.init_node("run_agent")
    config = rospy.get_param("~config")  # access parameters together as a dictionary

    ros_config = config.get("ros_config", {})
    runner = SloopMosAgentROSRunner(ros_config=ros_config)
    runner.setup()
    rate = rospy.Rate(5)
    ready = False
    while not rospy.is_shutdown():
        if runner.check_if_ready():
            ready = True
            break
        rate.sleep()
    if ready:
        agent = runner.make_agent(config)
        planner = runner.make_planner(config, agent)
        runner.set_planner(planner)
        runner.run()


if __name__ == "__main__":
    main()
