agent_config:
  agent_class: MosAgentTopo3D
  agent_type: local
  belief:
    init_params:
      num_samples: 3000
      occupancy_blow_up_res: 4
      occupancy_fill_height: true
      occupancy_height_thres: 0.2
      prior_from_occupancy: true
    visible_volume_params:
      num_rays: 150
      step_size: 0.2
      voxel_res: 2
  objects:
    Cup:
      class: cup
      color:
      - 0.67
      - 0.61
      - 0.15
      - 0.8
      transition:
        class: sloop_object_search.oopomdp.StaticObjectTransitionModel
      viz_type: cube
  robot:
    action:
      policy:
        cost_scaling_factor: 1.0
      topo:
        3d_proj_2d:
          brush_size: 0.2
          floor_cut: 0.15
          inflation: 0.5
          layout_cut: 0.4
        debug: false
        num_nodes: 10
        pos_importance_thres: 0.01
        resample_thres: 0.4
        sample_space:
          center_x: 0.0
          center_y: 2.0
          center_z: 0.0
          size_x: 2.0
          size_y: 4.0
          size_z: 1.5
        sep: 0.75
    detectors:
      Cup:
        class: sloop_object_search.oopomdp.FrustumVoxelAlphaBeta
        params:
          quality:
          - 10000000.0
          - 0.2
          sensor: gripper_camera
    id: robot0
    no_look: true
    reachable:
      max_height: 1.3
      min_height: 1.0
    sensors:
    - name: gripper_camera
      params:
        aspect_ratio: 0.7
        far: 1.5
        fov: 53
        near: 0.2
        occlusion_enabled: true
  search_region:
    3d:
      center_x: 0.0
      center_y: 0.0
      center_z: 0.0
      octree_size: 32
      point_cloud_from_world_state: true
      region_size_x: 1.35
      region_size_y: 2.4
      region_size_z: 1.5
      res: 0.08
  targets:
  - Cup
planner_config:
  planner: pomdp_py.POUCT
  planner_params:
    exploration_const: 1000
    max_depth: 6
    num_sims: 400
    show_progress: true
task_config:
  max_steps: 200
world_state_config:
- color:
  - 0.5
  - 0.8
  - 0.9
  - 0.8
  name: arm_origin
  pose:
  - 0.0
  - 0.0
  - 0.0
  sizes:
  - 0.17
  - 0.17
  - 0.25
- color:
  - 0.2
  - 0.2
  - 0.2
  - 0.8
  name: wall_behind
  pose:
  - 0.2
  - 0
  - 0.5
  sizes:
  - 0.08
  - 2.0
  - 2.0
- color:
  - 0.05
  - 0.45
  - 0.72
  - 0.8
  name: mount
  pose:
  - 0.3
  - 0.0
  - -0.5
  sizes:
  - 0.7
  - 1.0
  - 1.0
- color:
  - 0.9
  - 0.9
  - 0.9
  - 0.8
  name: table_below
  pose:
  - -0.45
  - 0.0
  - -0.27
  sizes:
  - 0.9
  - 1.9
  - 0.1
- color:
  - 0.9
  - 0.9
  - 0.9
  - 0.8
  name: table_far
  pose:
  - 0.05
  - -1.7
  - -0.27
  sizes:
  - 1.9
  - 0.8
  - 0.1
