python test_simple_sim_env_local_search_3d.py groundtruth 32 config_simple_sim_lab121_lidar.yaml
python test_simple_sim_env_local_search_3d.py uniform 32 config_simple_sim_lab121_lidar.yaml
python test_simple_sim_env_local_search_3d.py occupancy 32 config_simple_sim_lab121_lidar.yaml
python test_simple_sim_env_local_search_3d.py uniform 16 config_simple_sim_lab121_lidar.yaml
python test_simple_sim_env_local_search_3d.py occupancy 16 config_simple_sim_lab121_lidar.yaml
